package com.parsecgaming.parsec;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ParsecGuest extends Structure {
	/**
	 * Guest input permissions. ::HOST_DESKTOP only.<br>
	 * C type : ParsecPermissions
	 */
	public ParsecPermissions perms;
	/**
	 * Latency performance metrics, only valid in state ::GUEST_CONNECTED.<br>
	 * C type : ParsecMetrics
	 */
	public ParsecMetrics metrics;
	/**
	 * @see ParsecLibrary.ParsecGuestState
	 * Guest connection lifecycle states.<br>
	 * C type : ParsecGuestState
	 */
	public int state;
	/**  Guest ID passed to various host functions. */
	public int id;
	/**  Parsec unique user ID. */
	public int userID;
	/**
	 * UTF-8 null-terminated name guest name string.<br>
	 * C type : char[32]
	 */
	public byte[] name = new byte[32];
	/**  The guest is also the owner of the host computer. ::HOST_DESKTOP only. */
	public byte owner;
	/** C type : uint8_t[3] */
	public byte[] __pad = new byte[3];
	public ParsecGuest() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("perms", "metrics", "state", "id", "userID", "name", "owner", "__pad");
	}
	/**
	 * @param perms  Guest input permissions. ::HOST_DESKTOP only.<br>
	 * C type : ParsecPermissions<br>
	 * @param metrics  Latency performance metrics, only valid in state ::GUEST_CONNECTED.<br>
	 * C type : ParsecMetrics<br>
	 * @param state Guest connection lifecycle states.<br>
	 * C type : ParsecGuestState<br> @see ParsecGuestState<br>
	 * @param id  Guest ID passed to various host functions.<br>
	 * @param userID  Parsec unique user ID.<br>
	 * @param name  UTF-8 null-terminated name guest name string.<br>
	 * C type : char[32]<br>
	 * @param owner  The guest is also the owner of the host computer. ::HOST_DESKTOP only.<br>
	 * @param __pad C type : uint8_t[3]
	 */
	public ParsecGuest(ParsecPermissions perms, ParsecMetrics metrics, int state, int id, int userID, byte name[], byte owner, byte __pad[]) {
		super();
		this.perms = perms;
		this.metrics = metrics;
		this.state = state;
		this.id = id;
		this.userID = userID;
		if ((name.length != this.name.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.name = name;
		this.owner = owner;
		if ((__pad.length != this.__pad.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.__pad = __pad;
	}
	public ParsecGuest(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ParsecGuest implements Structure.ByReference {
		
	};
	public static class ByValue extends ParsecGuest implements Structure.ByValue {
		
	};
}
