package com.parsecgaming.parsec;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ParsecGuestStateChangeEvent extends Structure {
	/**
	 * < Guest properties. The `state` member can be used to evaluate the guest's state change.<br>
	 * C type : ParsecGuest
	 */
	public ParsecGuest guest;
	public ParsecGuestStateChangeEvent() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("guest");
	}
	/**
	 * @param guest < Guest properties. The `state` member can be used to evaluate the guest's state change.<br>
	 * C type : ParsecGuest
	 */
	public ParsecGuestStateChangeEvent(ParsecGuest guest) {
		super();
		this.guest = guest;
	}
	public ParsecGuestStateChangeEvent(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ParsecGuestStateChangeEvent implements Structure.ByReference {
		
	};
	public static class ByValue extends ParsecGuestStateChangeEvent implements Structure.ByValue {
		
	};
}
