package com.parsecgaming.parsec;
import com.parsecgaming.parsec.ParsecGuestStateChangeEvent;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.Union;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ParsecHostEvent extends Structure {
	/**
	 * @see ParsecLibrary.ParsecHostEventType
	 * < `ParsecHostEventType` event type.<br>
	 * C type : ParsecHostEventType
	 */
	public int type;
	/** C type : field1_union */
	public field1_union field1;
	/** <i>native declaration : line 727</i> */
	public static class field1_union extends Union {
		/**
		 * < Guest state change event.<br>
		 * C type : ParsecGuestStateChangeEvent
		 */
		public ParsecGuestStateChangeEvent guestStateChange;
		/**
		 * < User-defined guest message event.<br>
		 * C type : ParsecUserDataEvent
		 */
		public ParsecUserDataEvent userData;
		/**
		 * < New `serverID` event.<br>
		 * C type : ParsecServerIDEvent
		 */
		public ParsecServerIDEvent serverID;
		public field1_union() {
			super();
		}
		/**
		 * @param guestStateChange < Guest state change event.<br>
		 * C type : ParsecGuestStateChangeEvent
		 */
		public field1_union(ParsecGuestStateChangeEvent guestStateChange) {
			super();
			this.guestStateChange = guestStateChange;
			setType(ParsecGuestStateChangeEvent.class);
		}
		/**
		 * @param userData < User-defined guest message event.<br>
		 * C type : ParsecUserDataEvent
		 */
		public field1_union(ParsecUserDataEvent userData) {
			super();
			this.userData = userData;
			setType(ParsecUserDataEvent.class);
		}
		/**
		 * @param serverID < New `serverID` event.<br>
		 * C type : ParsecServerIDEvent
		 */
		public field1_union(ParsecServerIDEvent serverID) {
			super();
			this.serverID = serverID;
			setType(ParsecServerIDEvent.class);
		}
		public field1_union(Pointer peer) {
			super(peer);
		}
		public static class ByReference extends field1_union implements Structure.ByReference {
			
		};
		public static class ByValue extends field1_union implements Structure.ByValue {
			
		};
	};
	public ParsecHostEvent() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("type", "field1");
	}
	/**
	 * @param type @see ParsecHostEventType<br>
	 * < `ParsecHostEventType` event type.<br>
	 * C type : ParsecHostEventType<br>
	 * @param field1 C type : field1_union
	 */
	public ParsecHostEvent(int type, field1_union field1) {
		super();
		this.type = type;
		this.field1 = field1;
	}
	public ParsecHostEvent(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ParsecHostEvent implements Structure.ByReference {
		
	};
	public static class ByValue extends ParsecHostEvent implements Structure.ByValue {
		
	};
}
