package com.parsecgaming.parsec;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ParsecGamepadAxisMessage extends Structure {
	/**
	 * @see ParsecLibrary.ParsecGamepadAxis
	 * < Gamepad axes related to thumbsticks and triggers.<br>
	 * C type : ParsecGamepadAxis
	 */
	public int axis;
	/** < Unique client-provided index identifying the gamepad. */
	public int id;
	/** < The new value of the axis between -32,768 (left/down) and 32,767 (right/up). */
	public short value;
	/** C type : uint8_t[2] */
	public byte[] __pad = new byte[2];
	public ParsecGamepadAxisMessage() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("axis", "id", "value", "__pad");
	}
	/**
	 * @param axis @see ParsecGamepadAxis<br>
	 * < Gamepad axes related to thumbsticks and triggers.<br>
	 * C type : ParsecGamepadAxis<br>
	 * @param id < Unique client-provided index identifying the gamepad.<br>
	 * @param value < The new value of the axis between -32,768 (left/down) and 32,767 (right/up).<br>
	 * @param __pad C type : uint8_t[2]
	 */
	public ParsecGamepadAxisMessage(int axis, int id, short value, byte __pad[]) {
		super();
		this.axis = axis;
		this.id = id;
		this.value = value;
		if ((__pad.length != this.__pad.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.__pad = __pad;
	}
	public ParsecGamepadAxisMessage(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ParsecGamepadAxisMessage implements Structure.ByReference {
		
	};
	public static class ByValue extends ParsecGamepadAxisMessage implements Structure.ByValue {
		
	};
}
