package com.parsecgaming.parsec;
import com.ochafik.lang.jnaerator.runtime.NativeSize;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ParsecCursor extends Structure {
	/** < `true` if the cursor has switched absolute/relative mode. The `relative`, `positionX`, and `positionY` members are valid. */
	public byte modeUpdate;
	/** < `true` if the cursor has has an updated image. The `width`, `height`, `hotX`, `hotY`, and `size` members are valid. */
	public byte imageUpdate;
	/** < `true` if the host is in relative mode, indicating the client should probably send mouse motion in relative mode. */
	public byte relative;
	/** < Size in bytes of the cursor image buffer. */
	public NativeSize size;
	/** < Width of the cursor image in pixels. */
	public short width;
	/** < Height of the cursor position in pixels. */
	public short height;
	/** < Horizontal pixel position of the cursor hotspot within the image. */
	public short hotX;
	/** < Vertical pixel position of the cursor hotspot within the image. */
	public short hotY;
	/** < When the host leaves relative mode, the horizontal position in screen coordinates where the cursor reappears. */
	public short positionX;
	/** < When the host leaves relative mode, the vertical position in screen coordinates where the cursor reappears. */
	public short positionY;
	public ParsecCursor() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("modeUpdate", "imageUpdate", "relative", "size", "width", "height", "hotX", "hotY", "positionX", "positionY");
	}
	public ParsecCursor(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ParsecCursor implements Structure.ByReference {
		
	};
	public static class ByValue extends ParsecCursor implements Structure.ByValue {
		
	};
}
