package com.parsecgaming.parsec;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ParsecKeyboardMessage extends Structure {
	/**
	 * @see ParsecLibrary.ParsecKeycode
	 * < `ParsecKeymod` modifier key value.<br>
	 * C type : ParsecKeycode
	 */
	public int code;
	/**
	 * @see ParsecLibrary.ParsecKeymod
	 * < `ParsecKeycode` value.<br>
	 * C type : ParsecKeymod
	 */
	public int mod;
	/** < `true` if pressed, `false` if released. */
	public byte pressed;
	/** C type : uint8_t[3] */
	public byte[] __pad = new byte[3];
	public ParsecKeyboardMessage() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("code", "mod", "pressed", "__pad");
	}
	/**
	 * @param code @see ParsecKeycode<br>
	 * < `ParsecKeymod` modifier key value.<br>
	 * C type : ParsecKeycode<br>
	 * @param mod @see ParsecKeymod<br>
	 * < `ParsecKeycode` value.<br>
	 * C type : ParsecKeymod<br>
	 * @param pressed < `true` if pressed, `false` if released.<br>
	 * @param __pad C type : uint8_t[3]
	 */
	public ParsecKeyboardMessage(int code, int mod, byte pressed, byte __pad[]) {
		super();
		this.code = code;
		this.mod = mod;
		this.pressed = pressed;
		if ((__pad.length != this.__pad.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.__pad = __pad;
	}
	public ParsecKeyboardMessage(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ParsecKeyboardMessage implements Structure.ByReference {
		
	};
	public static class ByValue extends ParsecKeyboardMessage implements Structure.ByValue {
		
	};
}
