package com.parsecgaming.parsec;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ParsecHostConfig extends Structure {
	/** < Total number of guests allowed at once. */
	public int maxGuests;
	/** < Resolution width. */
	public int resolutionX;
	/** < Resolution height. */
	public int resolutionY;
	/** < Refresh rate in Hz. */
	public int refreshRate;
	/** < Mute local audio on owner connection. */
	public int adminMute;
	/** < Desired frames per second. */
	public int encoderFPS;
	/** < Maximum output bitrate in Mbps, split between guests. */
	public int encoderMaxBitrate;
	/** < Allow H.265 codec. */
	public int encoderH265;
	/** < Block remote input when local host input occurs. */
	public int exclusiveInput;
	public ParsecHostConfig() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("maxGuests", "resolutionX", "resolutionY", "refreshRate", "adminMute", "encoderFPS", "encoderMaxBitrate", "encoderH265", "exclusiveInput");
	}
	/**
	 * @param maxGuests < Total number of guests allowed at once.<br>
	 * @param resolutionX < Resolution width.<br>
	 * @param resolutionY < Resolution height.<br>
	 * @param refreshRate < Refresh rate in Hz.<br>
	 * @param adminMute < Mute local audio on owner connection.<br>
	 * @param encoderFPS < Desired frames per second.<br>
	 * @param encoderMaxBitrate < Maximum output bitrate in Mbps, split between guests.<br>
	 * @param encoderH265 < Allow H.265 codec.<br>
	 * @param exclusiveInput < Block remote input when local host input occurs.
	 */
	public ParsecHostConfig(int maxGuests, int resolutionX, int resolutionY, int refreshRate, int adminMute, int encoderFPS, int encoderMaxBitrate, int encoderH265, int exclusiveInput) {
		super();
		this.maxGuests = maxGuests;
		this.resolutionX = resolutionX;
		this.resolutionY = resolutionY;
		this.refreshRate = refreshRate;
		this.adminMute = adminMute;
		this.encoderFPS = encoderFPS;
		this.encoderMaxBitrate = encoderMaxBitrate;
		this.encoderH265 = encoderH265;
		this.exclusiveInput = exclusiveInput;
	}
	public ParsecHostConfig(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ParsecHostConfig implements Structure.ByReference {
		
	};
	public static class ByValue extends ParsecHostConfig implements Structure.ByValue {
		
	};
}
