package com.parsecgaming.parsec;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ParsecClientCursorEvent extends Structure {
	/**
	 * Cursor properties.<br>
	 * C type : ParsecCursor
	 */
	public ParsecCursor cursor;
	/**  Buffer lookup key passed to ::ParsecGetBuffer to retrieve the cursor image, if available. */
	public int key;
	public ParsecClientCursorEvent() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("cursor", "key");
	}
	/**
	 * @param cursor Cursor properties.<br>
	 * C type : ParsecCursor<br>
	 * @param key Buffer lookup key passed to ::ParsecGetBuffer to retrieve the cursor image, if available.
	 */
	public ParsecClientCursorEvent(ParsecCursor cursor, int key) {
		super();
		this.cursor = cursor;
		this.key = key;
	}
	public ParsecClientCursorEvent(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ParsecClientCursorEvent implements Structure.ByReference {
		
	};
	public static class ByValue extends ParsecClientCursorEvent implements Structure.ByValue {
		
	};
}
